
// Generated by Cadence Genus(TM) Synthesis Solution 19.12-s121_1
// Generated on: Oct 17 2021 13:41:06 IST (Oct 17 2021 08:11:06 UTC)

// Verification Directory fv/mod5_up 

module mod5_up(out, clk, reset);
  input clk, reset;
  output [2:0] out;
  wire clk, reset;
  wire [2:0] out;
  wire n_0, n_1, n_2, n_3;
  DFQZRM2RA \out_reg[2] (.CK (clk), .D (n_0), .RB (out[0]), .Q
       (out[2]));
  DFQZRM2RA \out_reg[1] (.CK (clk), .D (n_3), .RB (n_2), .Q (out[1]));
  MXB2M1RA g145(.A (n_1), .B (out[0]), .S (out[1]), .Z (n_2));
  AN2M2R g144(.A (n_3), .B (out[1]), .Z (n_0));
  NR2M2R g146(.A (out[2]), .B (reset), .Z (n_3));
  DFZRM2RA \out_reg[0] (.CK (clk), .D (n_3), .RB (n_1), .Q (out[0]),
       .QB (n_1));
endmodule

